### ISSUE TITLE
SLR: add documentation

### ISSUE THREAD

**Issue by targos** [mljs/regression#4]

**Comment by lpatiny** [comment]
@andcastillo We should check 
* how to write the documentation
* how it can be generated automatically
* where it should be available

I would suggest that on www.lactame.com next to each package we have the userguide

Some packages already have the document like:
https://www.lactame.com/visualizer/doc/couchdbAttachments.html
From where you can directly jump to the source code and see how the comments was written:
https://www.lactame.com/visualizer/doc/couchdbAttachments.js.html

@targos I like that the userguide is written with the code because it is at my point of view much easier to maintain but I don't know how easy it is to generate the documention especially in a project like ml that combines many other projects.
